### PR TITLE
Master update to work with both Py2 and Py 3

### PR DESCRIPTION
**Pull request by Mr-TaylorHobbs**
This build will not quite pass because of the apysigner and generic request signer not yet being on pypi. I am planning to wait until the office is a bit more healthy and jenkins is not lighting up like christmas to add them to pypi.

### CODE REVIEW

**Comment by mattjmorrison-imt** [comment]
@Mr-TaylorHobbs can you set up the dev_build for this repo?

**Comment by Mr-TaylorHobbs** [comment]
Triggering job.

**Comment by Mr-TaylorHobbs** [comment]
@mattjmorrison-imt Does this look good and ready to go?

**Comment by mattjmorrison-imt** [comment]
@Mr-TaylorHobbs I think so - ready for it to be merged?

**Comment by Mr-TaylorHobbs** [comment]
Ready

**Pull request merged**
