### PR TITLE
Back port PATCH and PUT request data 

### PR DESCRIPTION
**Pull request by Mr-TaylorHobbs**

### CODE REVIEW

**Comment by mattjmorrison-imt** [comment]
@Mr-TaylorHobbs what's a `PATH` request?

**Comment by mattjmorrison-imt** [comment]
@Mr-TaylorHobbs what ever happened to this guy?

**Comment by Mr-TaylorHobbs** [comment]
Github is glitching and not showing it on my "Open PRs" list... I'll fix up the tests so we can merge him.

**Comment by mattjmorrison-imt** [comment]
@Mr-TaylorHobbs what's the story with this guy?

**Comment by Mr-TaylorHobbs** [comment]
@mattjmorrison-imt locking in the tox version gave this guy the life he needed.

**Comment by mattjmorrison-imt** [comment]
if we push 0.8.1 onto pypi will anything in production pick this up tonight?

**Comment by Mr-TaylorHobbs** [comment]
0.8.1 is technically already on our pypi

**Comment by mattjmorrison-imt** [comment]
so merging this would do nothing is what you're saying...

**Comment by Mr-TaylorHobbs** [comment]
Pretty much

**Pull request merged**
