### PR TITLE
Bug Fix: Add support for JSON API

### PR DESCRIPTION
**Pull request by Mr-TaylorHobbs**

### CODE REVIEW

**Comment by Mr-TaylorHobbs** [comment]
Couple things wrong with this build. 
1) The 3.4 pyenv will never work, because the legacy branch doesn't support Py3.4
2) I do not know why the one test fails in the 2.7 env. I have all the same versions of everything locally and it passes for me.

**Comment by Mr-TaylorHobbs** [comment]
Going out to the machine and running the tests with the py27 env works as well...

**Comment by mattjmorrison-imt** [comment]
For the legacy branch... do we update the tox.ini file to only include the py27 environment?

**Comment by Mr-TaylorHobbs** [comment]
@mattjmorrison-imt as per our discussion yesterday I checked the order that the tests ran locally and on ci. They do in fact match...

**Comment by mattjmorrison-imt** [comment]
@Mr-TaylorHobbs so do all of these things match then?

- [ ] python versions
- [ ] python dependencies
- [ ] test order
- [ ] django settings

and it works when you run it on the jenkins node, but not when the jenkins job runs, right?

**Comment by Mr-TaylorHobbs** [comment]
Yes, it works when I go out to the box and run it there.

**Comment by mattjmorrison-imt** [comment]
@Mr-TaylorHobbs what's the status of this thing?

**Comment by Mr-TaylorHobbs** [comment]
I spent probably far too much time on it and could never get the build working properly. Tests all pass locally.

**Comment by mattjmorrison-imt** [comment]
Is this blocking something?

**Comment by Mr-TaylorHobbs** [comment]
No, and I'm unsure how valuable this will even be. I don't know what using the legacy branch will also use JSON API. I figure almost everything that uses JSON API will be on the Django 1.8+ branch.

**Comment by mattjmorrison-imt** [comment]
Alright, we'll just kill this for now then.

**Comment by Mr-TaylorHobbs** [comment]
Sounds good to me.

**Pull request closed without merging**
