### PR TITLE
Bug Fix: Include company in request headers for JSON API client

### PR DESCRIPTION
**Pull request by Mr-TaylorHobbs**

### CODE REVIEW

**Comment by madisona** [comment]
@Mr-TaylorHobbs @mattjmorrison 

Is there any more generic way to do this? Seems like adding this functionality explicitly as it is here couples the project very tightly with this concept of a "company" that may or may not be relevant in all scenarios.  Could it be passed in with a more generic set of arguments?

**Comment by Mr-TaylorHobbs** [comment]
My thought process while creating this PR was that company_tenant and JSON API are both projects that we plan to be using with just about all future applications. I am open to passing it more generically, if this is not the case.

**Comment by mattjmorrison-imt** [comment]
@madisona The point of this is to tightly couple this to company_tenant and JSON API, like @Mr-TaylorHobbs said. Since the plan is going forward, all of our APIs are going to be using company_tenant and JSON API, I think this is the right level of abstraction. Anything more generic and we should just use a different base class.

**Comment by madisona** [comment]
@mattjmorrison-imt that seems fine and makes sense... This is a completely open project at this time and published on pypi.python.org.  It looks like there are 7 other folks that have this project starred and 1 other fork outside of our team... what is the good citizen thing to do here? It seems adding this type of tight coupling is good internally for our team, but makes no sense to someone else who may happen to use it.

**Comment by mattjmorrison-imt** [comment]
@madisona that is a good point... I had forgotten about that detail...

**Comment by Mr-TaylorHobbs** [comment]
@mattjmorrison-imt @madisona What if we added `headers` as a possible parameter to the methods and then the methods could combine it with the class's headers?

**Comment by mattjmorrison-imt** [comment]
@Mr-TaylorHobbs company isn't a header through, it's part of the url...

**Comment by mattjmorrison-imt** [comment]
I'm wondering if this class, as is, should be moved to `apps.core.utility`, or maybe even a generic `apps.core.client`...

**Comment by Mr-TaylorHobbs** [comment]
This PR was only placing company on the headers. I could see some benefit in a generic `apps.core.client` that all future clients will inherit from.

**Comment by mattjmorrison-imt** [comment]
@Mr-TaylorHobbs for `company_tenant` doesn't the URL have to contain the company?

**Comment by Mr-TaylorHobbs** [comment]
It does. I was just speaking for this PR specifically. Company is going to have to be even more tightly coupled with this generic client, which I think adds credence to the `apps.core.client` idea.

**Comment by mattjmorrison-imt** [comment]
@Mr-TaylorHobbs let's do that.

**Pull request closed without merging**
