### PR TITLE
Enhancement: Remove readonly widget from private key field

### PR DESCRIPTION
**Pull request by Mr-TaylorHobbs**

### CODE REVIEW

**Comment by madisona** [comment]
@Mr-TaylorHobbs are you able to only apply the read only widget when in "change mode", but still let you enter whatever is necessary on "add mode"?  Is that the point here to be able to add credentials with whatever you want?

**Comment by stclair** [comment]
@madisona Are you thinking it needs to be protected in change mode?  I can't think of much benefit that would provide, aside maybe the accidental changing of a private key.

**Comment by madisona** [comment]
@stclair - yes, accidental change of the private key is the only thing I'd
be concerned about and is the reason it was put as read only in the first
place.

if it isn't trivial (quick research looks like it may be more involved than
I was thinking or hoping) then I don't think it is a big deal.

Or maybe simply adding the private key to the list view would make it
easier to copy the private key without being in "edit" mode... unless that
would make you more concerned about having the keys displayed on the screen

**Comment by stclair** [comment]
@madisona Since the admin isn't used outside of IMT, I don't have any major concerns with showing the keys in the list view.

**Pull request merged**
