### PR TITLE
Legacy update to work with Py 2 and Py 3

### PR DESCRIPTION
**Pull request by Mr-TaylorHobbs**
This build will not quite pass because of the apysigner and generic request signer not yet being on pypi. I am planning to wait until the office is a bit more healthy and jenkins is not lighting up like christmas to add them to pypi.

### CODE REVIEW

**Comment by Mr-TaylorHobbs** [comment]
I also need to push up the correct requirements for this PR, but do not have access to push.

**Comment by mattjmorrison-imt** [comment]
@Mr-TaylorHobbs it looks like the legacy branch needs protected also... let me know if/when you come across other repos that need that done.

**Comment by Mr-TaylorHobbs** [comment]
@mattjmorrison-imt does the repo need to be set up to build PRs for the legacy branch too?

**Comment by Mr-TaylorHobbs** [comment]
image

Not sure if my comment triggered it or if you made it at the same time...

**Comment by mattjmorrison-imt** [comment]
@Mr-TaylorHobbs I did nothing...

**Comment by Mr-TaylorHobbs** [comment]
Well huh. Cool either way I guess

**Pull request merged**
